variables:
  ISOLATION: "buildpipeline${CI_PIPELINE_ID}"

before_script:
  - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}

after_script:
  - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
  - docker-compose down -v

.build: &build
  stage: build
  script:
    - docker-compose build --pull ${CI_BUILD_NAME}
    - docker-compose run --rm ${CI_BUILD_NAME} php /tests/requirements.php
    - curl https://github.com/yiisoft/yii2/archive/master.zip -o yii.zip -L
    - unzip yii.zip -d tests
    - docker run -v ${PWD}/tests:/tests -w /tests/yii2-master composer install
    - docker-compose run -w /tests/yii2-master --rm ${CI_BUILD_NAME} vendor/bin/phpunit -v --exclude caching,db,data --log-junit tests/_junit/test.xml

php-5.6-apache:
  <<: *build

php-5.6-fpm:
  <<: *build

php-7.0-apache:
  <<: *build

php-7.0-fpm:
  <<: *build

php-7.1-apache:
  <<: *build

php-7.1-fpm:
  <<: *build
