version: '2'
services:
  web:
    image: phundament/nginx-one:1.9-5.1.1
    environment:
      - FASTCGI_PASS_HOST=php
    ports:
      - '8100:80'
    volumes:
      # Application testing
      - ./_host-volumes/app/web:/app/web:delegated