version: '2'
services:

  php:
    build:
      dockerfile: Dockerfile-fpm-${DOCKERFILE_FLAVOUR}
      context: 'php'
      args:
        - PHP_BASE_IMAGE_VERSION=${PHP_BASE_IMAGE_VERSION}
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
    volumes:
      - ./tests:/tests
      # Framework testing
      #- ./_host-volumes/app:/app:delegated
      #- ~/.composer-docker/cache:/root/.composer/cache:delegated
